-- Generated by scripts/generate-seed.mjs — initial catalog.
-- Safe to re-run: existing rows are left untouched.

insert into public.collections (handle, title, nav_group, position) values
  ('all-top', 'All Top', 'tops', 0),
  ('shirts', 'Shirts', 'tops', 1),
  ('t-shirts', 'T-Shirts', 'tops', 2),
  ('quarter-zipper', 'Sweatshirts', 'tops', 3),
  ('basics', 'Polo', 'tops', 4),
  ('frontpage', 'Drop Needle', 'autonomy', 5),
  ('bottoms', 'Bottoms', 'bottoms', 6),
  ('landing-page-collection', 'New In', 'featured', 7)
on conflict (handle) do nothing;

insert into public.products (id, handle, title, description, disclaimer, price,
                             compare_at_price, images, collections, status, position) values
  ('8834678849754', 'polo', 'Quad Vertical Rib Drop Needle Polo', 'A crafted polo in quad vertical drop needle knit, featuring defined rib lines that blend seamlessly with a soft, structured silhouette. The thick, high-weight fabric adds warmth and durability, while the clean, modern texture provides subtle depth and dimension for a sophisticated, contemporary look.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 2400, null, array['/images/polo-1.webp', '/images/polo-2.webp', '/images/polo-3.webp', '/images/polo-4.webp']::text[], array['frontpage', 'all-top', 'landing-page-collection']::text[], 'active', 0),
  ('8875592548570', 'micro-block-drop-needle-knit', 'Micro Block Texture Knit', 'High-weight polo crafted from micro-block drop needle knit, featuring a sophisticated silhouette at the collar and hem for a refined look. The thick, textured fabric provides warmth and comfort, making it ideal for lounge wear as well as winter layering.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 3700, null, array['/images/micro-block-drop-needle-knit-1.webp', '/images/micro-block-drop-needle-knit-2.webp', '/images/micro-block-drop-needle-knit-3.webp', '/images/micro-block-drop-needle-knit-4.webp']::text[], array['frontpage', 'all-top', 'landing-page-collection']::text[], 'active', 1),
  ('9165707313370', 'essential-pique-polo-black', 'Essential Piqué Polo - Black', 'A plain piqué polo crafted for daily use. This essential piece features a sophisticated silhouette and lightweight fabric, making it perfect for everyday wear with a clean finish.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 1700, null, array['/images/essential-pique-polo-black-1.webp', '/images/essential-pique-polo-black-2.webp']::text[], array['basics', 'all-top']::text[], 'active', 2),
  ('8875623710938', 'essential-pique-polo-green', 'Essential Piqué Polo - Green', 'A plain piqué polo crafted for daily use. This essential piece features a sophisticated silhouette and lightweight fabric, making it perfect for everyday wear with a clean finish.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 2200, null, array['/images/essential-pique-polo-green-1.webp', '/images/essential-pique-polo-green-2.webp']::text[], array['basics', 'all-top', 'landing-page-collection']::text[], 'active', 3),
  ('8875778834650', 'essential-pique-polo-charcoal', 'Essential Piqué Polo - Charcoal', 'A plain piqué polo crafted for daily use. This essential piece features a sophisticated silhouette and lightweight fabric, making it perfect for everyday wear with a clean finish.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 2200, null, array['/images/essential-pique-polo-charcoal-1.webp', '/images/essential-pique-polo-charcoal-2.webp']::text[], array['basics', 'all-top']::text[], 'active', 4),
  ('9082421346522', 'interlock-shirt-with-zip-closure', 'Light Weight Interlock Shirt', 'A lightweight, relaxed-fit shirt crafted from 100% cotton interlock fabric, featuring a sleek zip closure in solid black. The smooth texture and breathable construction make it ideal for layering or wearing on its own, offering a clean and casual look with effortless comfort. This is a lightweight interlock shirt, not a sweatshirt.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 1600, null, array['/images/interlock-shirt-with-zip-closure-1.webp', '/images/interlock-shirt-with-zip-closure-2.webp', '/images/interlock-shirt-with-zip-closure-3.webp', '/images/interlock-shirt-with-zip-closure-4.webp']::text[], array['shirts', 'all-top', 'landing-page-collection']::text[], 'active', 5),
  ('9082462273754', 'interlock-shirt-with-zip-closure-navy', 'Interlock Shirt with Zip Closure', 'A light-to-moderate weight, relaxed-fit shirt crafted from interlock fabric, featuring a sleek zip closure in navy blue. The smooth texture and polyester blend enhance durability while maintaining breathability, making it ideal for layering or wearing on its own. This is a moderate interlock shirt, not a sweatshirt.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 2300, null, array['/images/interlock-shirt-with-zip-closure-navy-1.webp', '/images/interlock-shirt-with-zip-closure-navy-2.webp', '/images/interlock-shirt-with-zip-closure-navy-3.webp']::text[], array['shirts', 'all-top', 'landing-page-collection']::text[], 'active', 6),
  ('9083175928026', 'yarn-dyed-stripe-tee', 'Yarn Dyed Stripe Tee', 'This lightweight navy blue and white striped shirt is crafted from yarn-dyed jersey knit, offering exceptional comfort and breathability in warm weather. Designed with a touch of Lycra, it ensures controlled stretch while maintaining its shape, providing a refined fit that moves with you. Perfect for casual layering or solo wear.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 2000, null, array['/images/yarn-dyed-stripe-tee-1.webp', '/images/yarn-dyed-stripe-tee-2.webp', '/images/yarn-dyed-stripe-tee-3.webp']::text[], array['t-shirts', 'all-top', 'landing-page-collection']::text[], 'active', 7),
  ('9015819993306', 'microgrid-quarter-zipper', 'Textured Quarter Zipper', 'A full-sleeve sweatshirt crafted from waffle thermal fabric, featuring ribbed hems and a minimalistic zip hook for a clean finish. The textured knit provides warmth and breathability, making it perfect for winter wear while maintaining a relaxed fit, whether layered or worn on its own.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 3800, null, array['/images/microgrid-quarter-zipper-1.webp', '/images/microgrid-quarter-zipper-2.webp', '/images/microgrid-quarter-zipper-3.webp', '/images/microgrid-quarter-zipper-4.webp']::text[], array['quarter-zipper', 'all-top']::text[], 'active', 8),
  ('8834655748314', 'tropical-pant-4', 'Relaxed Fit Interlock Knit Trouser', 'Engineered for fluid movement and effortless polish. These interlock trousers offer a smooth double-knit surface with natural stretch and subtle structure. The double button waistband and clean tailoring add precision.', 'Color tones may appear slightly different in imagery due to lighting conditions and display variations.', 3300, null, array['/images/tropical-pant-4-1.webp', '/images/tropical-pant-4-2.webp', '/images/tropical-pant-4-3.webp']::text[], array['bottoms']::text[], 'active', 9)
on conflict (id) do nothing;

insert into public.product_variants (product_id, size, stock, position) values
  ('8834678849754', 'S', 4, 0),
  ('8834678849754', 'M', 1, 1),
  ('8834678849754', 'L', 6, 2),
  ('8875592548570', 'S', 2, 0),
  ('8875592548570', 'M', 0, 1),
  ('8875592548570', 'L', 4, 2),
  ('9165707313370', 'S', 23, 0),
  ('9165707313370', 'M', 9, 1),
  ('9165707313370', 'L', 20, 2),
  ('8875623710938', 'S', 10, 0),
  ('8875623710938', 'M', 3, 1),
  ('8875623710938', 'L', 0, 2),
  ('8875778834650', 'S', 9, 0),
  ('8875778834650', 'M', 2, 1),
  ('8875778834650', 'L', 0, 2),
  ('9082421346522', 'S', 20, 0),
  ('9082421346522', 'M', 34, 1),
  ('9082421346522', 'L', 33, 2),
  ('9082462273754', 'S', 1, 0),
  ('9082462273754', 'M', 0, 1),
  ('9082462273754', 'L', 1, 2),
  ('9083175928026', 'S', 5, 0),
  ('9083175928026', 'M', 3, 1),
  ('9083175928026', 'L', 5, 2),
  ('9015819993306', 'S', 1, 0),
  ('9015819993306', 'M', 0, 1),
  ('9015819993306', 'L', 1, 2),
  ('8834655748314', 'S', 4, 0),
  ('8834655748314', 'M', 4, 1),
  ('8834655748314', 'L', 12, 2)
on conflict (product_id, size) do nothing;
