// One-off: localize Google Fonts into public/fonts + generate src/fonts.css,
// so the site has no external font dependency. Keeps every @font-face with its
// own unicode-range (full coverage, incl. basic Latin).
import fs from "node:fs/promises";
import path from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;1,400&family=Jost:wght@300;400;500&display=swap";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15";

const OUT = "public/fonts";
await fs.mkdir(OUT, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Each @font-face block carries its own src + unicode-range (correctly paired).
const blocks = css.split("@font-face").filter((b) => b.includes("src:"));
let outCss = "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs */\n";
let i = 0;

for (const b of blocks) {
  const fam = /font-family:\s*'([^']+)'/.exec(b)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(b)?.[1] || "400";
  const style = /font-style:\s*(\w+)/.exec(b)?.[1] || "normal";
  const range = /unicode-range:\s*([^;]+);/.exec(b)?.[1];
  const url = /url\((https:[^)]+\.woff2)\)/.exec(b)?.[1];
  if (!fam || !url) continue;

  const fname = `${fam.replace(/\s+/g, "")}-${weight}-${style}-${i++}.woff2`;
  const buf = Buffer.from(
    await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer()
  );
  await fs.writeFile(path.join(OUT, fname), buf);

  outCss +=
    `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url('/fonts/${fname}') format('woff2');` +
    (range ? `unicode-range:${range};` : "") +
    `}\n`;
}
await fs.writeFile("src/fonts.css", outCss);
const kb = (
  (await Promise.all(
    (await fs.readdir(OUT)).map(async (f) => (await fs.stat(path.join(OUT, f))).size)
  )).reduce((a, b) => a + b, 0) / 1024
).toFixed(0);
console.log(`wrote ${i} faces, ${kb}KB total`);
