// Writes supabase/seed.sql from the bundled catalog in src/data/store.js, so
// the database starts with exactly what the live site shows today.
// Product ids are kept, which keeps shoppers' existing carts/saved lists valid.
//
//   node scripts/generate-seed.mjs
//
// The seed is idempotent (ON CONFLICT DO NOTHING) — re-running it never
// overwrites edits made in the admin.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { collections, products } from "../src/data/store.js";

const q = (v) => (v == null ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (xs) =>
  xs.length ? `array[${xs.map(q).join(", ")}]::text[]` : `'{}'::text[]`;

const out = [
  "-- Generated by scripts/generate-seed.mjs — initial catalog.",
  "-- Safe to re-run: existing rows are left untouched.",
  "",
  "insert into public.collections (handle, title, nav_group, position) values",
  collections
    .map((c, i) => `  (${q(c.handle)}, ${q(c.title)}, ${q(c.group)}, ${i})`)
    .join(",\n"),
  "on conflict (handle) do nothing;",
  "",
  "insert into public.products (id, handle, title, description, disclaimer, price,",
  "                             compare_at_price, images, collections, status, position) values",
  products
    .map(
      (p, i) =>
        `  (${q(p.id)}, ${q(p.handle)}, ${q(p.title)}, ${q(p.description)}, ${q(
          p.disclaimer
        )}, ${p.price}, ${p.compareAtPrice ?? "null"}, ${arr(p.images)}, ${arr(
          p.collections
        )}, 'active', ${i})`
    )
    .join(",\n"),
  "on conflict (id) do nothing;",
  "",
  "insert into public.product_variants (product_id, size, stock, position) values",
  products
    .flatMap((p) =>
      p.sizes.map((s, i) => `  (${q(p.id)}, ${q(s.size)}, ${s.qty}, ${i})`)
    )
    .join(",\n"),
  "on conflict (product_id, size) do nothing;",
  "",
];

const target = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));
writeFileSync(target, out.join("\n"));
console.log(`Wrote ${target} — ${products.length} products, ${collections.length} collections`);
